### PR TITLE
Unified bastion module

### PR DESCRIPTION
**Pull request by igorkotof**
Features:
 - Move bastion host to private subnet without Public IP
 - Using SSM agent to connect to

Changes:
 - Restructuration
 - Added IAM resources for ssm
 - Removed Route53 items, removed public IP, set private subnet
 - Added AMI filter for bastion EC2
 - Terraform fmt

Testing:
Apply: https://asciinema.org/a/DQtlXEBJRGDXokb7u8ntGTSN2
	https://asciinema.org/a/jkuSEgVWjPVFShy5NGj6Mac7P
Destroy: https://asciinema.org/a/PYhkag5roucv0IDBg7aAeO1S0

### CODE REVIEW

**Comment by igorkotof** [comment]
[Create unified bastion module](https://trello.com/c/Io1MX305/93-create-unified-bastion-module)

**Comment by igorkotof** [comment]
[Resolve issue with filtering ssm enabled ami's](https://trello.com/c/E8RZX2GQ/92-resolve-issue-with-filtering-ssm-enabled-amis)

**Review by DimmKirr — APPROVED** [review]
Looks good to me. I'd say let's make sure to create a proper major version bump release.

**Review by kobrikx — APPROVED** [review]
Looks good to me.

**Comment by DimmKirr** [comment]
Yay, let's merge it @igorkotof

**Pull request merged**
